### ISSUE TITLE
BOOST_HOF_LIFT doesn't work correctly on latest MSVC 14.2

### ISSUE THREAD

**Issue by pdimov** [boostorg/hof#220]
https://godbolt.org/z/81bKWTx9M

Using BOOST_HOF_LIFT at function scope fails with

```
<source>(14): error C2951: template declarations are only permitted at global, namespace, or class scope
<source>(14): error C2892: a template cannot be a member of a local class
<source>(15): fatal error C1506: unrecoverable block scoping error
```

whereas it works correctly under GCC and Clang. The reason is probably https://github.com/boostorg/hof/blob/0a28586156eb6cc7db1fbe74ae2a220daf40df14/include/boost/hof/lift.hpp#L89, which only checks whether `_MSC_VER` is defined, but not its value.

In addition, checking `_MSC_VER` before `__clang__` is wrong because clang-cl defines both.

**Comment by pdimov** [comment]
I don't know what versions of MSVC work correctly and what do not; which one did you test with when you added the workaround?
